### ISSUE TITLE
Smoothscroll seems to have stopped working in the latest version of Chrome [73]

### ISSUE THREAD

**Issue by pauljohnknight** [galambalazs/smoothscroll-for-websites#68]
Hi

In the latest version of Chrome [73.0.3683.75] the smooth scroll seems to have stopped working (and looks very jumpy). It's throwing an error in the console:

 `Unable to preventDefault inside passive event listener due to target being treated as passive`

In the console error message it links to this page to on the Chrome Platform Status:

https://www.chromestatus.com/features/6662647093133312

**Comment by EmilyChews** [comment]
I've encountered this issue as well on the latest Chrome. It seems Chrome are ignoring passive mouse-wheel event listeners on the window object going forward. This will break a lot of mouse-wheel related plugins.

**Comment by pauljohnknight** [comment]
Looking at the docs for this change it looks like you need to change the wheel event object boolean from true to false:

// this is now the default
`window.addEventListener("wheel", func, {passive: true} );`

//which needs to be changed to:

`window.addEventListener("wheel", func, {passive: false} );`

Explanation is given in the link below. I can't seem to work out where this will go in the code though?

The link the below can also be found on the page I've linked to in my original post on this thread

https://github.com/sahel-sh/Document-level-passive-wheel-event-listeners/blob/master/Explainer.md

**Comment by EmilyChews** [comment]
From what I can gather looking at the docs you can (effectively) turn this update off with some javascript. The problem is by the look of it @gblazex has his notifications turned off, so he probably won't see this issue for possibly weeks.

**Comment by gblazex** [comment]
This issue is already fixed boys.

Breathe easy

**Comment by pauljohnknight** [comment]
Why have you closed this issue when it hasn't been fixed @gblazex? Are you running the latest version of Chrome?

**Comment by EmilyChews** [comment]
Hi @gblazex - What @pauljohnknight says - it defo isn't working with the latest version of Chrome. I understand Elegant Themes have removed it from the latest Divi as well for the same reason.

**Comment by pauljohnknight** [comment]
...also I do appreciate you taking the time to write this and try and fix it. I didn't mean that last comment to sound off in any way.  But it definitely still isn't working (have tried the cdn code and non minified code in the repository).

**Comment by gblazex** [comment]
It is definitely working. Commit is 6 days old.

But I just checked it again for you guys.

Copy past the actual code from GitHub to a console on any website and you’ll see

Blaze

**Comment by pauljohnknight** [comment]
Ah yes all good and working now - must have been a caching issue. You're a legend thanks @gblazex @emilyChewsCheese - would recommend clearing your entire browser history instead of doing a hard-refersh.

**Comment by gblazex** [comment]
Yes thank you for reporting guys,

Have fun


Blaze

**Comment by prindacerk** [comment]
@gblazex has this been pushed to cdnjs yet? I only see the v1.4.8 and that has that error still.

https://cdnjs.com/libraries/smoothscroll

**Comment by gblazex** [comment]
I dunno what’s up w cdnjs 

I published the release and tag 1.4.9
It should grab it.

Maybe try cdnjs support


Blaze

**Comment by gblazex** [comment]
also updated npm which i forgot. maybe this will solve cdnjs too

**Comment by prindacerk** [comment]
Thanks but it's still in v1.4.8. Can you contact cdnjs and find out why? I messaged them but I think they didn't respond as I am not the author of the library.

**Comment by gblazex** [comment]
i think it is updated :)

**Comment by prindacerk** [comment]
Thank you. It's all good now.

**Comment by gblazex** [comment]
💗
